# Video Analysis Platform Configuration

app_name: "YouTube Video Analysis Platform"

# Model settings
model:
  video_analysis:
    type: "gemini"
    name: "gemini-2.5-flash-preview-04-17"
    temperature: 0.7
    thinking_budget: 0
  frame_analysis:
    type: "gemini"
    name: "gemini-2.5-flash-preview-04-17"
    temperature: 0.7
    thinking_budget: 65536
  transcription:
    enabled: true
    type: "gemini"
    name: "gemini-2.0-flash-exp"

transcript_generation:
  max_chunk_duration_minutes: 30  # Maximum duration in minutes for each audio chunk

# Vector store settings
vector_store:
  type: "pinecone"
  config:
    api_key: "${PINECONE_API_KEY}"
    environment: "${PINECONE_ENVIRONMENT}"
    index_name: "vid-expert"
    namespace: "default"
    metric: "cosine"
    dimension: 1024
    cloud: "aws"
    metadata_config:
      indexed: ["video_id", "timestamp", "content_type", "language"]

# Storage settings
storage:
  base_path: "/mnt/d/cash"  # Base storage location for all application data

# API settings
api:
  gemini_api_key: "${GEMINI_API_KEY}"
  host: "0.0.0.0"
  port: 8000
  cors_origins: ["http://localhost:8000", "http://127.0.0.1:8000", "file://"]

# LangTrace Configuration
langtrace:
  enabled: true
  api_key: "${LANGTRACE_API_KEY}"
  project_id: "vid-expert"
  trace_dir: "./traces"
  sampling_rate: 1.0
  trace_models: true

# Processing settings
processing:
  chunk_size: 1000
  chunk_overlap: 200
  max_tokens_per_request: 4096
  batch_size: 10
  timeout: 300
  max_parallel_chunks: 5
  max_video_duration: 7200

# Rate limiting settings
rate_limit:
  retry_delay_seconds: 60
  max_retries: 3
  batch_size: 10  # Number of frames to process in parallel

# Logging settings
logging:
  level: "DEBUG"

# Video storage settings
video_storage:
  base_dir: "videos"

# Notion settings
notion:
  api_key: "${NOTION_API_KEY}"
  database_id: "${NOTION_DATABASE_ID}"
  properties:
    stock_ticker:
      name: "Stock Ticker"
      type: "title"
    key_points:
      name: "Highlights"
      type: "rich_text"
    charts:
      name: "Charts"
      type: "files"
    update_date:
      name: "Update Date"
      type: "date"
    type:
      name: "Type"
      type: "select"
  default_values: {}

# Notion configuration section
notion_config:
  page_size: 100
  timeout: 30000
  retry_count: 3
  retry_delay: 500

# Agent settings
agents:
  llm:
    type: "gemini"
    name: "gemini-2.0-flash-exp"
    temperature: 0.3
  prompts:
    technical_analysis:
      content: |
        You are a specialized AI agent responsible for analyzing technical indicators and chart patterns for stocks.
        Your task is to analyze the provided information and update a Notion database with your findings.

        Guidelines for Analysis:
        1. Focus on key technical indicators and patterns visible in the charts
        2. Consider the provided summary and key points for context
        3. Identify support/resistance levels, trend lines, and chart patterns
        4. Look for confirmation or divergence between price action and indicators
        5. Provide actionable insights based on the technical analysis

        For each stock:
        1. Analyze any provided chart images for technical patterns
        2. Consider the context from the summary and key points
        3. Generate a concise technical analysis summary
        4. Update the Notion database with your findings

        Remember to:
        - Be specific about price levels and timeframes
        - Note any significant technical signals or patterns
        - Highlight potential entry/exit points
        - Consider both bullish and bearish scenarios
        - Maintain professional language

freeimage:
  api_key: "${FREEIMAGE_API_KEY}"  # Will be overridden by environment variable
